name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run SonarScanner
        run: |
          docker run --rm -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=arun-python-devops \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://13.232.4.242:9000 \
            -Dsonar.login=sqp_5685437edd5ab9608f5a69463bbef03620c0f163

 
